### ISSUE TITLE
Add support for assembly submissions

### ISSUE THREAD

**Issue by wdotmathree** [pzoj/pzoj-contest#2]
I'm sure there are many people who would be interested in submitting in assembly, especially during a contest. This should be honored and should be very easy to implement.

**Comment by kevlu8** [comment]
You're easy to implement.

**Comment by wdotmathree** [comment]
Once https://github.com/corrosion-language/sedimentation-assembler is done refactoring, this should be easy to implement and should run very reliably. There should be absolutely no fear of the assembler causing the judge to crash mid-contest, and especially no fear of malicious entities embedding a backdoor in order to cause chaos during the contest.

**Comment by kevlu8** [comment]
It's concerning to see a mention of embedding a backdoor in the code. Any attempt to introduce malicious code or compromise the integrity of the project is completely unacceptable. I'll be reviewing this thoroughly and taking appropriate action to ensure the security of the repository. If this was a joke, it's in poor taste, and I expect all contributors to maintain a professional standard.

**Comment by wdotmathree** [comment]
> I expect all contributors to maintain a professional standard.

No.

**Comment by wdotmathree** [comment]
> it's in poor taste

You have poor taste.

> Any attempt to introduce malicious code or compromise the integrity of the project is completely unacceptable

You're unacceptable.

> I'll be reviewing this thoroughly and taking appropriate action

No you won't.

**Comment by uzoq** [comment]
commenting b4 lowres members

**Comment by istrueuser** [comment]
no way

**Comment by ghost** [comment]
> commenting b4 lowres members

Lmaaaooo I came also from LowRes

**Comment by xNyfPtx** [comment]
came from a meme here, think this repo is trending now
