### ISSUE TITLE
Move compiler paths/args to top of file

### ISSUE THREAD

**Issue by wdotmathree** [pzoj/pzoj-contest#4]
This change will enable users to easily change the compiler to their preferred one. Currently, the user would have to dig through the codebase to find the part where the compilers are called, which is annoying since the file is so long. Further pushing for this change, the sedimentation assembler bundled with this repository is still in development and very bug prone, so if the user wants a more stable experience, they would most likely want to switch it out for nasm or another equivalent for the time being.

**Comment by kevlu8** [comment]
Is it possible to auto detect compiler paths using tools like CMake? If so, we could simply opt for that.

**Comment by wdotmathree** [comment]
I believe that is possible. I will be looking into that right now.

**Comment by Ashthetik** [comment]
> Is it possible to auto detect compiler paths using tools like CMake? If so, we could simply opt for that.

You can set the compiler in CMake with `set(CMAKE_CXX_COMPILER yourCompilerHere)` and it'll autodetect the compiler's path and auto-call it when you run `cmake -B .`
